import AppKit

final class OverlayView: NSView {
    private let blurView = NSVisualEffectView()
    private let tintView = NSView()
    private let maskLayer = CAShapeLayer()
    private var holeRects: [CGRect] = []

    init(frame frameRect: NSRect, config: AppConfig) {
        super.init(frame: frameRect)
        wantsLayer = true

        blurView.material = .underWindowBackground
        blurView.blendingMode = .behindWindow
        blurView.state = .active
        blurView.alphaValue = config.blurAlpha
        blurView.autoresizingMask = [.width, .height]
        blurView.frame = bounds
        addSubview(blurView)

        tintView.wantsLayer = true
        tintView.layer?.backgroundColor = NSColor.black.withAlphaComponent(config.dimAlpha).cgColor
        tintView.autoresizingMask = [.width, .height]
        tintView.frame = bounds
        addSubview(tintView)

        maskLayer.actions = ["path": NSNull(), "frame": NSNull()]
        layer?.mask = maskLayer
        updateMask()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func layout() {
        super.layout()
        blurView.frame = bounds
        tintView.frame = bounds
        updateMask()
    }

    func setBlurAlpha(_ value: CGFloat) {
        blurView.alphaValue = value
    }

    func setDimAlpha(_ value: CGFloat) {
        tintView.layer?.backgroundColor = NSColor.black.withAlphaComponent(value).cgColor
    }

    func setHoleRects(_ rects: [CGRect]) {
        holeRects = rects
        updateMask()
    }

    // MARK: - Mask Computation

    private func updateMask() {
        let p = CGMutablePath()
        p.addRect(bounds)
        for (holeRect, shouldRound) in mergedHoleRects() {
            let clamped = holeRect.intersection(bounds)
            if !clamped.isEmpty {
                if shouldRound {
                    let maxCorner = min(12, clamped.width / 2, clamped.height / 2)
                    p.addRoundedRect(in: clamped, cornerWidth: maxCorner, cornerHeight: maxCorner)
                } else {
                    p.addRect(clamped)
                }
            }
        }
        maskLayer.frame = bounds
        maskLayer.path = p
        maskLayer.fillRule = .evenOdd
        maskLayer.fillColor = NSColor.black.cgColor
    }

    /// A hole rect paired with whether it should be drawn with rounded corners.
    /// Primary holes keep rounded corners; strips generated by subtraction use square corners
    /// so adjacent strip junctions don't leave gaps where their rounded corners would meet.
    private typealias HoleEntry = (rect: CGRect, shouldRound: Bool)

    /// Returns a non-overlapping set of HoleEntries covering the union of all hole rects.
    /// Each input rect is split into pieces that don't overlap with previously added rects,
    /// so every pixel is inside exactly one hole — even-odd always sees count=2 (outer+hole)
    /// and makes the whole union transparent, with no cancellation in overlap areas.
    private func mergedHoleRects() -> [HoleEntry] {
        var result: [HoleEntry] = []
        for rect in holeRects where !rect.isNull && !rect.isEmpty {
            var parts: [HoleEntry] = [(rect: rect, shouldRound: true)]
            for (existing, _) in result {
                parts = parts.flatMap { (r, round) -> [HoleEntry] in
                    let pieces = subtractRect(existing, from: r)
                    if pieces.count == 1 && pieces[0] == r { return [(rect: r, shouldRound: round)] }
                    return pieces.map { (rect: $0, shouldRound: false) }
                }
            }
            result.append(contentsOf: parts)
        }
        return result
    }

    /// Returns the parts of `rect` that lie outside `sub` (up to 4 non-overlapping rects).
    private func subtractRect(_ sub: CGRect, from rect: CGRect) -> [CGRect] {
        guard rect.intersects(sub) else { return [rect] }
        let i = rect.intersection(sub)
        var parts: [CGRect] = []
        if rect.minY < i.minY {
            parts.append(CGRect(x: rect.minX, y: rect.minY, width: rect.width, height: i.minY - rect.minY))
        }
        if rect.maxY > i.maxY {
            parts.append(CGRect(x: rect.minX, y: i.maxY, width: rect.width, height: rect.maxY - i.maxY))
        }
        if rect.minX < i.minX {
            parts.append(CGRect(x: rect.minX, y: i.minY, width: i.minX - rect.minX, height: i.height))
        }
        if rect.maxX > i.maxX {
            parts.append(CGRect(x: i.maxX, y: i.minY, width: rect.maxX - i.maxX, height: i.height))
        }
        return parts
    }
}
